# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gevir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_transcript', models.CharField(max_length=20, verbose_name='Canonical Transcript')),
                ('xstart', models.IntegerField(verbose_name='xStart')),
                ('xstop', models.IntegerField(verbose_name='xStart')),
            ],
        ),
        migrations.CreateModel(
            name='VariantIntolerantRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrom', models.CharField(max_length=2, verbose_name='Chrom')),
                ('strand', models.CharField(max_length=1, verbose_name='Strand')),
                ('start', models.IntegerField(verbose_name='Start')),
                ('stop', models.IntegerField(verbose_name='Stop')),
                ('canonical_transcript', models.CharField(max_length=20, verbose_name='Canonical Transcript')),
                ('region_filter', models.CharField(max_length=20, verbose_name='Filter')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('exome_coverage', models.FloatField(verbose_name='Exome Coverage')),
                ('gerp_mean', models.FloatField(verbose_name='GERP++ (mean)')),
                ('percentile', models.FloatField(verbose_name='Region Percentile')),
                ('xstart', models.IntegerField(verbose_name='xStart')),
                ('xstop', models.IntegerField(verbose_name='xStart')),
                ('codon_xstart', models.IntegerField(verbose_name='Codon xStart')),
                ('codon_xstop', models.IntegerField(verbose_name='Codon xStop')),
                ('start_variant', models.CharField(max_length=50, verbose_name='Start Variant')),
                ('start_variant_csq', models.CharField(max_length=50, verbose_name='Start Variant Consequence')),
                ('stop_variant', models.CharField(max_length=50, verbose_name='Stop Variant')),
                ('stop_variant_csq', models.CharField(max_length=50, verbose_name='Stop Variant Consequence')),
            ],
        ),
    ]
