# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gevir', '0002_codingregion_variantintolerantregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingregion',
            name='xstart',
            field=models.IntegerField(db_index=True, verbose_name='xStart'),
        ),
        migrations.AlterField(
            model_name='codingregion',
            name='xstop',
            field=models.IntegerField(db_index=True, verbose_name='xStart'),
        ),
        migrations.AlterField(
            model_name='geneidentifier',
            name='gene_identifier_upper',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='genescore',
            name='canonical_transcript',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Canonical Transcript'),
        ),
        migrations.AlterField(
            model_name='variantintolerantregion',
            name='codon_xstart',
            field=models.IntegerField(db_index=True, verbose_name='Codon xStart'),
        ),
        migrations.AlterField(
            model_name='variantintolerantregion',
            name='codon_xstop',
            field=models.IntegerField(db_index=True, verbose_name='Codon xStop'),
        ),
        migrations.AlterField(
            model_name='variantintolerantregion',
            name='xstart',
            field=models.IntegerField(db_index=True, verbose_name='xStart'),
        ),
        migrations.AlterField(
            model_name='variantintolerantregion',
            name='xstop',
            field=models.IntegerField(db_index=True, verbose_name='xStart'),
        ),
    ]
