# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-20 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gevir', '0003_auto_20181220_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingregion',
            name='xstart',
            field=models.IntegerField(verbose_name='xStart'),
        ),
        migrations.AlterField(
            model_name='codingregion',
            name='xstop',
            field=models.IntegerField(verbose_name='xStart'),
        ),
        migrations.AlterField(
            model_name='variantintolerantregion',
            name='codon_xstart',
            field=models.IntegerField(verbose_name='Codon xStart'),
        ),
        migrations.AlterField(
            model_name='variantintolerantregion',
            name='codon_xstop',
            field=models.IntegerField(verbose_name='Codon xStop'),
        ),
        migrations.AlterField(
            model_name='variantintolerantregion',
            name='xstart',
            field=models.IntegerField(verbose_name='xStart'),
        ),
        migrations.AlterField(
            model_name='variantintolerantregion',
            name='xstop',
            field=models.IntegerField(verbose_name='xStart'),
        ),
        migrations.AddIndex(
            model_name='variantintolerantregion',
            index=models.Index(fields=['xstart', 'xstop'], name='gevir_varia_xstart_b03195_idx'),
        ),
        migrations.AddIndex(
            model_name='variantintolerantregion',
            index=models.Index(fields=['codon_xstart', 'codon_xstop'], name='gevir_varia_codon_x_d60c25_idx'),
        ),
        migrations.AddIndex(
            model_name='codingregion',
            index=models.Index(fields=['xstart', 'xstop'], name='gevir_codin_xstart_06a0ce_idx'),
        ),
    ]
